---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Congress

<!-- badges: start -->
<!-- badges: end -->

The goal of Congress is to provide information about US Congressional representatives throughout history.

## Installation

You can install the released version of Congress from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("Congress")
```

## Example

This is a graph of the number of terms vs percent of legislation passed for representatives in the US Congress.

```{r example}
library(Congress)
library(ggplot2)
Congress <- readRDS(file = "data.Rds")

ggplot(Congress,
  aes(x = number_terms, y = pass_prcnt)) +
  geom_point() + 
  geom_smooth(se = FALSE) + 
  labs(title = "Number of Terms vs Percent of Legislation Passed", 
       x = "Number of Congressional Terms", 
       y = "Percent of Legislation Passed while Serving")
```
